### ISSUE TITLE
Add a reference in your page

### ISSUE THREAD

**Issue by applicato** [lonekorean/gist-syntax-themes#2]
Hi. Сould you, pls, tell me how to do this? In pictures.

**Comment by lonekorean** [comment]
It's the same as adding any other stylesheet to a page.

```html
<link href="monokai.css" rel="stylesheet">
```

There's not really anything to take a picture of.

**Comment by applicato** [comment]
ok, sorry for bothering you, but this is not rendered as it should:
https://gist.github.com/akkuraten/7d8784fc7d2e8f274f00c248a48a97ca

UPD on your site" not on gist. Ok, get it.
